//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smshatirlatma.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borc
    {
        public int id { get; set; }
        public Nullable<int> islemturu { get; set; }
        public Nullable<System.DateTime> zaman { get; set; }
        public Nullable<int> kayitid { get; set; }
        public Nullable<int> satisid { get; set; }
        public Nullable<decimal> tutar { get; set; }
        public Nullable<System.DateTime> alacakzaman { get; set; }
    
        public virtual kayit kayit { get; set; }
        public virtual satis satis { get; set; }
    }
}
