//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smshatirlatma.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenelLog
    {
        public int id { get; set; }
        public Nullable<int> islem { get; set; }
        public string tablo { get; set; }
        public Nullable<int> tablo_id { get; set; }
        public Nullable<System.DateTime> zaman { get; set; }
        public string aciklama { get; set; }
    }
}
