//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smshatirlatma.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gozluk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gozluk()
        {
            this.satis = new HashSet<satis>();
        }
    
        public int id { get; set; }
        public string kod { get; set; }
        public Nullable<int> adet { get; set; }
        public Nullable<int> sekilid { get; set; }
        public Nullable<int> camid { get; set; }
        public Nullable<int> markaid { get; set; }
        public Nullable<bool> gonderim { get; set; }
        public Nullable<bool> aktif { get; set; }
    
        public virtual CamTipleri CamTipleri { get; set; }
        public virtual Marka Marka { get; set; }
        public virtual SekilTipi SekilTipi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satis> satis { get; set; }
    }
}
