//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smshatirlatma.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesajKontrol
    {
        public int id { get; set; }
        public Nullable<int> kayitid { get; set; }
        public string mesaj { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual kayit kayit { get; set; }
    }
}
