//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smshatirlatma.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public satis()
        {
            this.Borc = new HashSet<Borc>();
        }
    
        public int id { get; set; }
        public int tutar { get; set; }
        public Nullable<System.DateTime> zaman { get; set; }
        public Nullable<int> Kayitid { get; set; }
        public Nullable<int> Gozlukid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borc> Borc { get; set; }
        public virtual Gozluk Gozluk { get; set; }
        public virtual kayit kayit { get; set; }
    }
}
