//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smshatirlatma.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sms
    {
        public int id { get; set; }
        public Nullable<bool> özel { get; set; }
        public Nullable<System.DateTime> zaman { get; set; }
        public string mesajmetni { get; set; }
        public string kisiadı { get; set; }
        public string kisitel { get; set; }
    }
}
